### ISSUE TITLE
Crashes on invalid parameters.

### ISSUE THREAD

**Issue by PeterCamilleri** [PeterCamilleri/connect_n_game#2]
For example:

```
11 mysh>connect_n_game help

Welcome to the Connect N Command Line Interface.
This is game version: 0.0.2.

Player Selection:
  Basic     Minimum tactical analysis.
  Bruce     An actual player.
  Echo      Really unoriginal.
  Human     An actual player.
  Middle    Moves toward the middle
  Prudent   Minimum tactical analysis with some defense.
  Random    Moves randomly.
  Sheila    An actual player.

Enter player 1 name: C:/RailsInstaller/Ruby2.3.3/lib/ruby/gems/2.3.0/gems/connec
t_n_game-0.0.2/lib/cli/select_players.rb:24:in `gets': No such file or directory
 @ rb_sysopen - help (Errno::ENOENT)
        from C:/RailsInstaller/Ruby2.3.3/lib/ruby/gems/2.3.0/gems/connect_n_game
-0.0.2/lib/cli/select_players.rb:24:in `gets'
        from C:/RailsInstaller/Ruby2.3.3/lib/ruby/gems/2.3.0/gems/connect_n_game
-0.0.2/lib/cli/select_players.rb:24:in `pick_a_player'
        from C:/RailsInstaller/Ruby2.3.3/lib/ruby/gems/2.3.0/gems/connect_n_game
-0.0.2/lib/cli/select_players.rb:16:in `top_up_players'
        from C:/RailsInstaller/Ruby2.3.3/lib/ruby/gems/2.3.0/gems/connect_n_game
-0.0.2/lib/cli/cli.rb:28:in `main'
        from C:/RailsInstaller/Ruby2.3.3/lib/ruby/gems/2.3.0/gems/connect_n_game
-0.0.2/bin/connect_n_game:16:in `<top (required)>'
        from C:/RailsInstaller/Ruby2.3.3/bin/connect_n_game:22:in `load'
        from C:/RailsInstaller/Ruby2.3.3/bin/connect_n_game:22:in `<main>'

```

**Comment by PeterCamilleri** [comment]
Fixed in version 0.0.3
